library(xlsx)
library(tidyverse)
Developmental_Disorders <- read_excel("C:/Users/jojo1/Downloads/Developmental Disorders.xlsx")
Developmental_Disorders$Gender <- as.factor(Developmental_Disorders$Gender)
dd <- Developmental_Disorders %>% mutate(Gender = ifelse(Gender == "M", 0, 1))
suppressPackageStartupMessages(library(caret))
set.seed(23)
dd$Diagnostic.Group <- factor(dd$Diagnostic.Group, levels = c("ASD", "SDD", "ID"))
trainIndex <- createDataPartition(dd$Diagnostic.Group, times = 1, p = 0.8, list = FALSE)
train <- dd[trainIndex,]
test <- dd[-trainIndex,]
preProcValues <- preProcess(train, method = c("center", "scale"))
trainproc <- predict(preProcValues, train)
testproc <- predict(preProcValues, test)
trainControl <- trainControl(method="repeatedcv", number=10, repeats=5)
grid <- expand.grid(.k=seq(1,20,by=1))
knnModel <- train(Diagnostic.Group~., data = trainproc, method = "knn", trControl = trainControl, tuneGrid = grid)
print(knnModel)
plot(knnModel)
best_model <- knn3(Diagnostic.Group~., data = trainproc, k = knnModel$bestTune$k)
predictions <- predict(best_model, testproc, type = "class")
cm <- confusionMatrix(predictions, testproc$Diagnostic.Group)
cm
library(pROC)
multiclass.roc(response = testproc$Diagnostic.Group, predictor = as.ordered(predictions))
